# Generated by Django 4.1.5 on 2023-03-21 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Administrador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50, unique=True)),
                (
                    "telefone",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="(XX)XXXXX-XXXX"
                    ),
                ),
                ("dataNascimento", models.DateField()),
                (
                    "documento",
                    models.CharField(
                        help_text="Insira seu CPF",
                        max_length=14,
                        unique=True,
                        verbose_name="XXX.XXX.XXX-XX",
                    ),
                ),
                ("senha", models.CharField(max_length=50)),
                ("dataCriacao", models.DateTimeField(auto_now_add=True)),
                ("dataAtualizacao", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50, unique=True)),
                (
                    "telefone",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="(XX)XXXXX-XXXX"
                    ),
                ),
                (
                    "documento",
                    models.CharField(
                        help_text="Insira seu CNPJ",
                        max_length=18,
                        unique=True,
                        verbose_name="XX.XXX.XXX/XXXX-XX",
                    ),
                ),
                ("senha", models.CharField(max_length=50)),
                ("dataCriacao", models.DateTimeField(auto_now_add=True)),
                ("dataAtualizacao", models.DateTimeField(auto_now=True)),
                (
                    "administrador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.administrador",
                    ),
                ),
            ],
        ),
    ]
