# Generated by Django 4.1.5 on 2023-03-28 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50, unique=True)),
                (
                    "telefone",
                    models.CharField(
                        help_text="(XX)XXXXX-XXXX", max_length=15, unique=True
                    ),
                ),
                ("dataNascimento", models.DateField()),
                (
                    "documento",
                    models.CharField(
                        help_text="Insira seu CPF", max_length=14, unique=True
                    ),
                ),
                ("senha", models.CharField(max_length=50)),
                ("dataCriacao", models.DateTimeField(auto_now_add=True)),
                ("dataAtualizacao", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Marca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=80)),
                ("pais", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Modelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.marca",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Moto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataFabricacao", models.DateTimeField(auto_now_add=True)),
                (
                    "modelo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.modelo",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="administrador",
            name="documento",
            field=models.CharField(
                help_text="Insira seu CPF", max_length=14, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="administrador",
            name="telefone",
            field=models.CharField(
                help_text="(XX)XXXXX-XXXX", max_length=15, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="documento",
            field=models.CharField(
                help_text="Insira seu CNPJ", max_length=18, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="telefone",
            field=models.CharField(
                help_text="(XX)XXXXX-XXXX", max_length=15, unique=True
            ),
        ),
        migrations.CreateModel(
            name="Venda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataVenda", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.cliente",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.empresa",
                    ),
                ),
                (
                    "moto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cadastros.moto"
                    ),
                ),
            ],
        ),
    ]
