# Generated by Django 4.1.5 on 2023-03-28 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0002_cliente_marca_modelo_moto_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empresa",
            name="senha",
        ),
    ]
