# Generated by Django 4.1.5 on 2023-05-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0003_remove_empresa_senha"),
    ]

    operations = [
        migrations.AddField(
            model_name="moto",
            name="preco",
            field=models.FloatField(default=0.0, verbose_name="Preço Unitário"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="moto",
            name="quantidade",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="administrador",
            name="dataAtualizacao",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="administrador",
            name="dataCriacao",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="administrador",
            name="dataNascimento",
            field=models.DateField(verbose_name="Data de Nascimento"),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="dataAtualizacao",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="dataCriacao",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="dataNascimento",
            field=models.DateField(verbose_name="Data de Nascimento"),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="dataAtualizacao",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="dataCriacao",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="marca",
            name="pais",
            field=models.CharField(max_length=50, verbose_name="País"),
        ),
        migrations.AlterField(
            model_name="moto",
            name="dataFabricacao",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="venda",
            name="dataVenda",
            field=models.DateField(auto_now_add=True),
        ),
    ]
