# Generated by Django 4.1.5 on 2023-05-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0004_moto_preco_moto_quantidade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrador",
            name="dataAtualizacao",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="administrador",
            name="dataCriacao",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="administrador",
            name="dataNascimento",
            field=models.DateTimeField(verbose_name="Data de Nascimento"),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="dataAtualizacao",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="dataCriacao",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="dataNascimento",
            field=models.DateTimeField(verbose_name="Data de Nascimento"),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="dataAtualizacao",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="dataCriacao",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="moto",
            name="dataFabricacao",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="venda",
            name="dataVenda",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
