# Generated by Django 4.1.5 on 2023-05-30 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0005_alter_administrador_dataatualizacao_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venda",
            name="moto",
        ),
        migrations.CreateModel(
            name="MotoVenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preco", models.FloatField(verbose_name="Preço Unitário")),
                ("quantidade", models.IntegerField()),
                (
                    "moto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cadastros.moto"
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.venda",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Carrinho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField()),
                (
                    "moto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cadastros.moto"
                    ),
                ),
            ],
        ),
    ]
