# Generated by Django 4.1.5 on 2023-06-27 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0010_remove_venda_moto_remove_venda_valor"),
    ]

    operations = [
        migrations.AddField(
            model_name="venda",
            name="moto",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="cadastros.moto",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="venda",
            name="valor",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
