# Generated by Django 4.1.5 on 2023-07-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0011_venda_moto_venda_valor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venda",
            name="moto",
        ),
        migrations.AlterField(
            model_name="venda",
            name="valor",
            field=models.FloatField(default=0.0),
        ),
    ]
