# Generated by Django 4.1.5 on 2023-08-07 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cadastros", "0012_remove_venda_moto_alter_venda_valor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="usuario",
        ),
        migrations.AddField(
            model_name="cliente",
            name="cadastrado_por",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
