# Generated by Django 4.1.5 on 2023-09-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0013_remove_cliente_usuario_cliente_cadastrado_por"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="bairro",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cliente",
            name="cep",
            field=models.CharField(default="", max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cliente",
            name="cidade",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cliente",
            name="logradouro",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cliente",
            name="numero",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cliente",
            name="uf",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
