# Generated by Django 4.1.5 on 2023-09-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0014_cliente_bairro_cliente_cep_cliente_cidade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="cep",
            field=models.CharField(max_length=9, verbose_name="CEP"),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="numero",
            field=models.CharField(max_length=50, verbose_name="Número"),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="uf",
            field=models.CharField(max_length=50, verbose_name="UF"),
        ),
    ]
