# Generated by Django 4.1.5 on 2023-10-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0015_alter_cliente_cep_alter_cliente_numero_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moto",
            name="preco",
            field=models.DecimalField(
                decimal_places=2, max_digits=13, verbose_name="Preço Unitário"
            ),
        ),
        migrations.AlterField(
            model_name="motovenda",
            name="preco",
            field=models.DecimalField(
                decimal_places=2, max_digits=13, verbose_name="Preço Unitário"
            ),
        ),
        migrations.AlterField(
            model_name="venda",
            name="valor",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=13),
        ),
    ]
