# Generated by Django 4.1.5 on 2023-10-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0016_alter_moto_preco_alter_motovenda_preco_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venda",
            name="valor",
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
    ]
